version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  build: "./taskfiles/build.yaml"
  deps: "./taskfiles/deps.yaml"
  lint: "./taskfiles/lint.yaml"
  test: "./taskfiles/test.yaml"
  utils: "./tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"
  G_CPP_SRC_DIR: "{{.ROOT_DIR}}/src"

  G_VALID_BUILD_TYPES:
    - "debug"
    - "release"
  G_VALID_TARGETS:
    - "all"
    - "containers"
    - "error_handling"
    - "wrapped_facade_headers"

tasks:
  clean:
    desc: "Removes the project build directory."
    cmds:
      - "rm -rf '{{.G_BUILD_DIR}}'"

  init:
    internal: true
    silent: true
    run: "once"
    cmds:
      - "mkdir -p '{{.G_BUILD_DIR}}'"

  validate-args:
    internal: true
    requires:
      vars: ["BUILD_TYPE", "TARGET"]
    cmds:
      - task: "validate-build-type"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
      - task: "validate-target"
        vars:
          TARGET: "{{.TARGET}}"

  validate-build-type:
    internal: true
    requires:
      vars: ["BUILD_TYPE"]
    preconditions:
      - sh: >-
          {{has .BUILD_TYPE .G_VALID_BUILD_TYPES}}
        msg: |-
          {{- if not (has .BUILD_TYPE .G_VALID_BUILD_TYPES)}}
            {{.BUILD_TYPE}} is not a valid build type. List of valid build types:
            {{- range .G_VALID_BUILD_TYPES}}
              {{.}}
            {{- end}}
          {{- end}}

  validate-target:
    internal: true
    requires:
      vars: ["TARGET"]
    preconditions:
      - sh: >-
          {{has .TARGET .G_VALID_TARGETS}}
        msg: |-
          {{- if not (has .TARGET .G_VALID_TARGETS)}}
            {{.TARGET}} is not a valid build target. List of valid build targets:
            {{- range .G_VALID_TARGETS}}
              {{.}}
            {{- end}}
          {{- end}}
