version: "3"

includes:
  deps:
    internal: true
    taskfile: "deps.yaml"
  utils:
    internal: true
    taskfile: "../tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

tasks:
  build-*-*:
    desc: "build-<target>-<build type>: Builds the specified build target with build type."
    vars:
      BUILD_TYPE: "{{index .MATCH 1}}"
      TARGET: "{{index .MATCH 0}}"
    deps:
      - task: ":validate-args"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "build"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"

  clean-*:
    desc: "clean-<build type>: Clean the build type."
    vars:
      BUILD_TYPE: "{{index .MATCH 0}}"
    deps:
      - task: ":validate-build-type"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
    cmds:
      - task: "utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"

  install-*-*:
    desc: >-
      install-<target>-<build type> INSTALL_PREFIX="<prefix path>": Install the specified build
      target with build type to the prefix path.
    vars:
      BUILD_TYPE: "{{index .MATCH 1}}"
      TARGET: "{{index .MATCH 0}}"
    requires:
      vars: ["INSTALL_PREFIX"]
    deps:
      - task: ":validate-args"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "install"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          INSTALL_PREFIX: "{{.INSTALL_PREFIX}}"
          TARGET: "{{.TARGET}}"

  build:
    internal: true
    requires:
      vars: ["BUILD_TYPE", "TARGET"]
    deps:
      - "deps:all"
    cmds:
      - task: "utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE={{.BUILD_TYPE}}"
          SOURCE_DIR: "{{.ROOT_DIR}}"
      - task: "utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          TARGETS:
            - "{{.TARGET}}"

  install:
    internal: true
    dir: "{{.USER_WORKING_DIR}}"  # relative INSTALL_PREFIX will be evaluated to current directory
    vars:
      ABSOLUTE_INSTALL_PREFIX:
        sh: 'echo $(realpath {{.INSTALL_PREFIX}})'
    requires:
      vars: ["BUILD_TYPE", "INSTALL_PREFIX", "TARGET"]
    deps:
      - task: "build"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "utils:cmake:install"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          INSTALL_PREFIX: "{{.ABSOLUTE_INSTALL_PREFIX}}"
          EXTRA_ARGS: ["{{if not (eq .TARGET \"all\")}}--component {{.TARGET}}{{end}}"]
