version: "3"

includes:
  deps:
    internal: true
    taskfile: "deps.yaml"
  utils:
    internal: true
    taskfile: "../tools/yscope-dev-utils/exports/taskfiles/utils/utils.yaml"

vars:
  G_EXAMPLES_BUILD_DIR: "{{.G_BUILD_DIR}}/examples"

tasks:
  build-*-*:
    desc: "build-<target>-<build type>: Builds the specified build target with build type."
    vars:
      BUILD_TYPE: "{{index .MATCH 1}}"
      TARGET: "{{index .MATCH 0}}"
    deps:
      - task: ":validate-args"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "build"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"

  clean-*:
    desc: "clean-<build type>: Clean the build type."
    vars:
      BUILD_TYPE: "{{index .MATCH 0}}"
    deps:
      - task: ":validate-build-type"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
    cmds:
      - task: "utils:cmake:clean"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"

  examples-*:
    desc: "examples-<build type>: Builds the examples with build type."
    vars:
      BUILD_TYPE: "{{index .MATCH 0}}"
    deps:
      - task: ":validate-build-type"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
    cmds:
      - task: "examples"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"

  install-*-*:
    desc: >-
      install-<target>-<build type> INSTALL_PREFIX="<prefix path>": Install the specified build
      target with build type to the prefix path.
    vars:
      BUILD_TYPE: "{{index .MATCH 1}}"
      TARGET: "{{index .MATCH 0}}"
    requires:
      vars: ["INSTALL_PREFIX"]
    deps:
      - task: ":validate-args"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "install"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          INSTALL_PREFIX: "{{.INSTALL_PREFIX}}"
          TARGET: "{{.TARGET}}"

  build:
    internal: true
    requires:
      vars: ["BUILD_TYPE", "TARGET"]
    deps:
      - "deps:all"
    cmds:
      - task: "utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE={{.BUILD_TYPE}}"
          SOURCE_DIR: "{{.ROOT_DIR}}"
      - task: "utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          TARGETS:
            - "{{.TARGET}}"

  examples:
    internal: true
    requires:
      vars: ["BUILD_TYPE"]
    vars:
      INSTALL_PREFIX: "{{.G_EXAMPLES_BUILD_DIR}}/deps/ystdlib/{{.BUILD_TYPE}}"
    deps:
      - task: "install"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          INSTALL_PREFIX: "{{.INSTALL_PREFIX}}"
          TARGET: "all"
    cmds:
      - task: "utils:cmake:generate"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/{{.BUILD_TYPE}}"
          EXTRA_ARGS:
            - "-DCMAKE_BUILD_TYPE={{.BUILD_TYPE}}"
            - "-Dystdlib_ROOT={{.INSTALL_PREFIX}}"
          SOURCE_DIR: "{{.ROOT_DIR}}/examples"
      - task: "utils:cmake:build"
        vars:
          BUILD_DIR: "{{.G_EXAMPLES_BUILD_DIR}}/{{.BUILD_TYPE}}"

  install:
    internal: true
    requires:
      vars: ["BUILD_TYPE", "INSTALL_PREFIX", "TARGET"]
    deps:
      - task: "build"
        vars:
          BUILD_TYPE: "{{.BUILD_TYPE}}"
          TARGET: "{{.TARGET}}"
    cmds:
      - task: "utils:cmake:install"
        vars:
          BUILD_DIR: "{{.G_YSTDLIB_BUILD_DIR}}/{{.BUILD_TYPE}}"
          INSTALL_PREFIX: "{{.INSTALL_PREFIX}}"
